version: '3.9'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ~/app/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_DATABASE=valentine
      - MYSQL_CONNECTION_STRING=mysql+pymysql://user:secret@localhost:3306/valentine
    restart: always


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:8080
    environment:
      - PMA_ARBITRARY=1
